### ISSUE TITLE
Visual block mode needs to be added to galaxyline config

### ISSUE THREAD

**Issue by mvphilip** [Iron-E/nvim-libmodal#11]
Hello, The ^V (visual block mode) is missing from the galaxyline config example. To fix just add this line:

	['^V']  = {'V-BLOCK',        _COLORS.blue},

Thanks,

-mp

**Comment by Iron-E** [comment]
I'm currently working on an overhaul on the `feature/001--lua-runtime` branch. It has an updated README which I should probably just cherry-pick.

Thanks for bringing this up!

**Comment by Iron-E** [comment]
The README has been updated. Thanks again!
