### ISSUE TITLE
Indicator functionality within a Layer, OR cursor functionality within a Mode.

### ISSUE THREAD

**Issue by jacksanders-xyz** [Iron-E/nvim-libmodal#12]
Hello!
Really love the plugin (I can't believe this hasn't blown up... such a good idea) 

I wanted to ask a quick question/or maybe suggest a feature: I am currently working on building a plugin that allows the user to write musical notation inside of nvim.  One mode (called score mode) will allow the user's curser to draw in musical symbols by performing all of the steps required to insert the specific UTF characters. Thus it needs to be able to move around and retain the cursor functionality.

I realize I could do this with a layer BUT I lose the super cool named indicator... I also want to create several submodes under this so an indicator would allow the user to keep track of where they are.

So I was curious as to HOW the plugin accesses nvim's Indicator (and is able to write --INSERT-- or --MY_MODE--) and is it possible to have a mode that also retains the cursor... OR is it possible to have a layer that allows you the indicator. (either would work).

Thanks!

**Comment by Iron-E** [comment]
There are a couple of possibilities here, so you can approach it from different angles.

The first (and what I do) is enable `cursorcolumn` and `cursorline`, and pass any unrecognized key command into normal mode so the cursor can be moved. This will show a coordinate for where the cursor is on the screen.

The other option is to use a custom statusbar (e.g. `feline`; see the README) and show the current layer name that way. This has the drawback of requiring a plugin for the user, but the upside of showing the cursor innately.

**Comment by jacksanders-xyz** [comment]
Ahh worked perfectly! 
Thanks so much!
