### ISSUE TITLE
Bad styling

### ISSUE THREAD

**Issue by anuvyklack** [Iron-E/nvim-libmodal#15]
In every Lua style guide this one:
```lua
local foo =
{
    bar = 2,
}
```
considered as a bad stlyle, and this one:
```lua
local foo = {
    bar = 2,
}
```
as a good one:

- https://github.com/luarocks/lua-style-guide
- https://docs.coregames.com/tutorials/lua_style_guide/#styling

**Comment by Iron-E** [comment]
I prefer newlines for every opening brace, as it helps clarify scope.
