### ISSUE TITLE
feline archieved switch to lualine?

### ISSUE THREAD

**Issue by 616b2f** [Iron-E/nvim-libmodal#18]
Hi, I wanted to try out your plugin but didn't found an example how to show the mods in lualine, then I saw that you use feline and saw that it's archived by the owner, do you plan to switch to some other plugin like lualine?

If yes, I would love to see your configuration for nvim-libmodal for it.

**Comment by Iron-E** [comment]
This is the first I've heard of feline.nvim being archived— thank you for letting me know. I'll definitely be switching to another plugin.

FWIW any statusline plugin that allows a custom component will be able to support this plugin. I'll take a look at the awesome-nvim repo and see if I can't cook up some examples

**Comment by Iron-E** [comment]
I have added a minimal `lualine` example to the repo

**Comment by 616b2f** [comment]
Awesome, thank you so much! I will try it out later today.

**Comment by Iron-E** [comment]
Gonna close as complete for now. If you have any further problems feel free to reopen
