### ISSUE TITLE
Layers don't seem to be reusable

### ISSUE THREAD

**Issue by itsFrank** [Iron-E/nvim-libmodal#19]
This may be by design, but the OOP api for creating layer makes it seem like they should be reusable.

--------------------------

**Repro**

I created this simple layer using the OOP api:
```lua
local layer = libmodal.layer.new({})

local count = 1
layer:map("n", "a", function()
	print("From layer - " .. tostring(count))
	count = count + 1
end, {})

layer:map("n", "<esc>", function()
	layer:exit()
end, {})

vim.keymap.set("n", "<leader>l", function()
	layer:enter()
end, {})
```

**Expected**
I can enter and exit the layer multiple times. When the layer is active the `a` keybind prints the message

**Actual**
The layer works fine the first time it is entered, but if it is exited and re-entered afterwards, none of the keybinds defined in the layer work.

-----------------------------

It feels like a layer should be able to be exited and re-entered without having to set all the keybinds on the layer object every-time it is exited.

**Comment by Iron-E** [comment]
You're right, this is an oversight. I'll see what I can do.
