### ISSUE TITLE
Error in command causes mode to exit

### ISSUE THREAD

**Issue by DavidGamba** [Iron-E/nvim-libmodal#2]
Hi @Iron-E,

This plugin is something I have been wanting to find for quite a while.
I was about to start playing with `kana/vim-submode` which doens't seem to be maintained anymore but thankfully I found this project too.

Thanks so much for such a cool plugin. I was able to write my first vim plugin thanks to some copy paste from your tabmode project.
Please take a look: https://github.com/DavidGamba/nvim-window-mode

I couldn't figure out how to handle errors (https://github.com/DavidGamba/nvim-window-mode/issues/1) so when there is an error in the command then it exits the mode. I would like to stay in the mode I am in regardless of the error. Thankfully neovim is displaying the error so at least I can see why I am no longer in that mode.

**Comment by Iron-E** [comment]
Thanks for the bug report! I'm glad to hear that `nvim-libmodal` made creating your plugin easier.

I am able to reproduce this issue with `nvim-tabmode` as well. Exiting a mode automatically because of an error is definitely unintended, so I'll take a look at this and report back.

**Comment by Iron-E** [comment]
I've set up a `bugfix/0.6.2` branch to allow verification that this issue has been resolved before merging into master. If you use `vim-plug` you can test it out using the following line in your `init.vim`:

```viml
Plug 'Iron-E/nvim-libmodal', {'branch': 'bugfix/0.6.2'}
```

It's working on my side, so it _should_ be working for you as well.

**Comment by DavidGamba** [comment]
@Iron-E thanks for the super fast response, just validated this branch works as intended.

**Comment by Iron-E** [comment]
Thanks for the confirmation, I just merged this so it'll be in master now. Glad I could help!
