### ISSUE TITLE
Error encountered: Expected lua string

### ISSUE THREAD

**Issue by chardskarth** [Iron-E/nvim-libmodal#21]
Error message:
```
E5108: Error executing lua: ...k/packer/start/nvim-libmodal/lua/libmodal/utils/Help.lua:41: Expected lua string
stack traceback:
        [C]: in function 'nvim_strwidth'
        ...k/packer/start/nvim-libmodal/lua/libmodal/utils/Help.lua:41: in function 'new'
        ...te/pack/packer/start/nvim-libmodal/lua/libmodal/Mode.lua:217: in function 'new'
        ...te/pack/packer/start/nvim-libmodal/lua/libmodal/init.lua:35: in function 'enter'
        /Users/rgdpro/.config/nvim/lua/my/whichkey-functions.lua:38: in function 'windowlayer'
        ...g/nvim/lua/plugins/windows-splits-tabs-buffer-motion.lua:71: in function <...g/nvim/lua/plugins/windows-splits-tabs-buffer-motion.lua:70>
```

Part of the stack trace is when Help message was constructed?

It's trying to get "nvim_strwidth" of a function? Here's my libmodal.mode.enter.
![image](https://user-images.githubusercontent.com/26249511/233977735-c0f57d8e-ff19-4bf4-9bc2-855fcb7972ae.png)

**Comment by AlexKurisu** [comment]
Same issue, no idea what's happening

**Comment by Iron-E** [comment]
Did this mode previously work, and now it is broken? Or is this something new that never worked?

**Comment by Iron-E** [comment]
Thanks for testing. Use that version for now and I'll work on this as soon as I can

**Comment by chardskarth** [comment]
Thanks!  Using `v3.3.0` and its working for me.

**Comment by Iron-E** [comment]
Sorry for the delay, I've been busy with [another project](https://github.com/Iron-E/nvim-highlite).

I can reproduce. I will issue a fix soon
