### ISSUE TITLE
Bug: cursor movements aren't updated until after leaving mode

### ISSUE THREAD

**Issue by mawkler** [Iron-E/nvim-libmodal#24]
Hi! First of all, thank you for making this super cool plugin!

I'm trying to create a custom mode using nvim-libmodal in which the cursor moves. However, the cursor movement isn't actually rendered until after leaving the mode.

Here's just a small example setup to illustrate the issue:

```lua
local libmodal = require 'libmodal'

vim.o.cursorline = true
vim.o.showmode   = false

local my_mode = {
  g = function() vim.api.nvim_win_set_cursor(0, { 1, 0 }) end,
}

vim.keymap.set('n', 'M', function()
  libmodal.mode.enter('my_mode', my_mode)
end)
```

To reproduce:

1. Move to the bottom of a file
2. Press `M` to enter `my_mode`
3. Press `g` to trigger custom action
4. Notice how cursorline moves to the top of the file, but the cursor is still drawn in the same spot as it were before you pressed `g`

I'm on Neovim nightly v0.10.0-dev-2355+g1c7b0b9d5

**Comment by Iron-E** [comment]
Thanks for the report! I'll take a look at this.

Two small workarounds I thought of for now:

1. Use `cursorcolumn` and `cursorline` 
2. Use a `layer` instead of a `mode`

**Comment by mawkler** [comment]
@Iron-E Ok, thank you!

**Comment by mawkler** [comment]
Yes, your PR seems to fix my issue. Thank you very much!
