### ISSUE TITLE
Bug: `vim.v.count` is always 0

### ISSUE THREAD

**Issue by mawkler** [Iron-E/nvim-libmodal#25]
Hi! I'm trying to use `vim.v.count` in a mode mapping. However, it seems to always be 0.

To reproduce:

```lua
local my_mode = {
  g = function()
    vim.notify('count: ' .. vim.v.count)
  end
}

vim.keymap.set('n', 'M', function()
  require('libmodal').mode.enter('My mode', my_mode)
end)
```

- Press `M`
- Press `3g`
- Notification says `count: 0`

**Comment by Iron-E** [comment]
This should hopefully be a simple fix. Thanks for bringing it to my attention!

I have some time to look at this and the other issue today

**Comment by Iron-E** [comment]
I've pushed to a new branch. `v:count` can't be updated manually, so I've created an alternate facility which tracks count until commands are executed:

```lua
local my_mode = {
	g = function()
		vim.notify('count: ' .. vim.g.myModeModeCount)
	end
}

vim.keymap.set('n', 'M', function()
	require('libmodal').mode.enter('My mode', my_mode)
end)
```

Let me know if this will work for you :)

**Comment by mawkler** [comment]
Too bad `v:count` can't be set manually. It doesn't look as clean but it does work for me. Thank you :)

**Comment by Iron-E** [comment]
Given that https://github.com/Iron-E/nvim-libmodal/pull/30 allows the `self` param, I can add `self.count` in a followup PR. That might look a little nicer 😅

**Comment by mawkler** [comment]
Yeah that might be a good idea 🙂

**Comment by mawkler** [comment]
Awesome! Thank you!
