### ISSUE TITLE
_Catch All_ Mode mapping

### ISSUE THREAD

**Issue by CHr15W3** [Iron-E/nvim-libmodal#39]
Hi,
Is there a canonical way to do a _catch all_ mapping, i.e. a default what should happen if a key is pressed that is not part of the mode?
Thanks a lot!

**Comment by Iron-E** [comment]
This could be achieved with the [functional API](https://github.com/Iron-E/nvim-libmodal/blob/master/examples%2Flua%2Fkeymaps-manually.lua), though the alternate table implementation cannot do this.

Is this suitable for your use case or would it be beneficial to use tables for this?

**Comment by Iron-E** [comment]
Does #39 fit your use case?
