### ISSUE TITLE
Importing libmodal prevents pasting into command prompt

### ISSUE THREAD

**Issue by DanCardin** [Iron-E/nvim-libmodal#4]
As far as i know this is the most basic use of this plugin:

In my vimrc:
```
lua require'foo'
```

in `lua/foo.lua`
```
local libmodal = require('libmodal')
```

This causes pasting into the command prompt (i.e. `:` -> `cmd+v`/whatever you bind paste to) to do nothing.

**Comment by Iron-E** [comment]
Thank you for the bug report! I can reproduce this issue and will investigate it promptly. I will report back with any findings and fixes as they come.

**Comment by Iron-E** [comment]
After investigation it appears to be a problem with importing `libmodal.utils.api` table. I'll do more investigation after work today, but I've narrowed it down for the time being.

**Comment by Iron-E** [comment]
I have a PR active right now that should fix this issue. If you can confirm that it has been fixed I will merge it! If you use `vim-plug` you can do so with the following line in your `init.vim`:

```vim
Plug 'Iron-E/nvim-libmodal', {'branch': 'bugfix/0.6.3'}
```

**Comment by DanCardin** [comment]
The branch seems to fix it! Thanks!

**Comment by Iron-E** [comment]
Great! Thanks for confirming. I'll merge it now.
